// number 삽입 이미지 개수
// serialize 연속으로 이미지 삽입(width hight StartPosition-X StartPosition-Y, center_x, center_y)
// pos 단일로 이미지 삽입 (width hight StartPosition-X StartPosition-Y)
number 86
texture "icon\icon_iconMessenger.dds" 0xffff00ff
serialize 6 32 32  1   1 0 0 // 큰 직업 아이콘 
serialize 6 32 32  1  33 0 0 // 큰 직업 아이콘 
serialize 6 16 16  1  65 0 0 // 작은 직업 아이콘 
serialize 6 16 16  1  81 0 0 // 작은 직업 아이콘 
serialize 3 16 16  1  97 0 0 // 친구, 그룹, 길드 항목아이콘 
serialize 6 12 12  1 113 0 0 // 큰 상태
serialize 6  8  8 73 113 0 0 // 작은 상태 
//추가분/////////////////////////////////////////
serialize 10 16 16 1 125 0 0 // 서버 아이콘
serialize 5 16 16  1 141 0 0 // 길드 호칭 아이콘
//추가분 2차직업/////////////////////////////////
serialize 8 32 32  1 157 0 0 // 2차 큰 직업 아이콘
serialize 8 32 32  1 189 0 0 // 2차 큰 직업 아이콘
serialize 8 16 16  1 221 0 0 // 2차 작은 직업 아이콘
serialize 8 16 16  1 237 0 0 // 2차 작은 직업 아이콘
