#b#cff0000ff Couple Skill Info.#nb#nc
* Skills are automatically acquired after reaching certain skill level
* Acquired skills will be automatically activated when connected with partner in same channel

#b#cff0000ff Couple Skill Type#nb#nc
* Power of Love
 - Level1 : Attack Power+20, Defense Power+10
             (Couple Level6 needed)
 - Level2 : Attack Power+40, Defense Power+20
             (Couple Level11 needed)
 - Level3 : Attack Power+60, Defense Power+30
             (Couple Level16 needed)
 - Level4 : Attack Power+80, Defense Power+40
             (Couple Level21 needed)
* Bless of Love
 - Level1 : Exp point+4%
             (Couple Level11 needed)
 - Level2 : Exp point+8%
             (Couple Level21 needed)
* Miracle of Love
 - Level1 : Drop Rate+5%
             (Couple Level21 needed)

#b#cffff0000¡Ø Breaking up with partner will reset the couple skill to Level 0.#nb#nc
