#b#cff0000ff* Participation Info.#nb#nc
* Application Period :  (Sun) 00:00~ (Sat) 17:00
* Location : 1st sub server
* Qualification
 - Only the Guild Leader can apply for Guild Sieges.
 - Guild must be at least level 20.
 - Guild Members must be higher than level 30.
 - Guild Leaders or Kingpins must be added to the Participation List.
 - The Top 8 that pay the highest Application Fee will be accepted into the Guild Siege.
* Time Table
 - 18:00  Entry starts  
 - 18:10  Entry ends
 - 18:11  Battle starts 

#b#cffff0000Guild Siege begins if 2 or more Guilds have applied.#nb#nc
