#b#cff0000ff* Win Condition Between Participants#nb#nc
 - You win when your opponents HP reaches 0.
#b#cff0000ff* Draw Condition Between Participants#nb#nc
 - If the battle does not finish within 10 minutes it is declared a draw.

#b#cff0000ff*  Win Condition for Participating Guilds#nb#nc
 - The Guild with the most winning members wins.
#b#cff0000ff* Draw Condition for Participating Guilds#nb#nc
 - If both Guilds have the same number of winning members the Siege is declared a Draw.
