#b#cff0000ff* Basic Rules#nb#nc
 - 1 on 1 Battle between 2 players.
 - Buffs and Party skills will be removed as players enter the Arena.
 - The Audience and the Participants will have no interaction.
 - 11 members from each Guild can join.
 - If there is no opponent you will win by default.
 - Red Chips will be given to individual winners and to the overall winning Guild.

#b#cffff0000 You cannot apply to the 1vs1 Guild Siege and Guild Siege at the same time.#nb#nc
