                               #cffC6E2FF#b#uFlyFF Version 15#nb#nu
                              Welcome to FlyFF!

            We hope you enjoy your stay in Madrigal.  
For the latest events, contests, and general information about FlyFF, check out our discussion forums located at:
                     #u#bhttp://flyff-forum.gpotato.com/#nb#nu

   To contact a Game Master regarding in-game issues:
                   #cff0099CC#b#uhttp://flyff.gpotato.com/?m=ticket#nb#nu#nc


Happy FlyFFing,
#bThe FlyFF Game Master Team#nb






