#b#cff0000ffRainbow Race Rules#nb#nc
1. All players that succesfully applied during the application window and are currently online will be admitted into the race.
2. There are 7 mini games that must be completed and they are given to each player in a random order.
3. After the player completes all of the mini-games, they must return to the Rainbow Race Officer in Darken City to confirm completion of the race.
4. During the Rainbow Race, some skills and items will be unavailable to prevent abuse.  Coral Island Tickets and Azria Tickets will be disabled.  Lord Skills are allowed.



