#b#cff0000ffRainbow Race Rewards#nb#nc
1st place: 50% of all application fees
2nd place: 24% of all application fees
3rd place: 12% of all application fees
4th place:  6% of all application fees
5th place:  3% of all application fees
6th place: 1.5% of all application fees
7th~10th:Less than 1.5% of all application fees

Please note: In addition to the percentage of all application fees being rewarded, top finalists will receive Rainbow Boxes as a bonus reward in their mailbox.