#b#cff0000ffWhat is Rainbow Race?#nb#nc
The Rainbow Race is a weekly event that all players can participate in.
\nApplications are accepted from:
12:01AM to 2:00PM (PST) every Saturday.
\nThe game starts every Saturday at 3:30PM PST 
\nThe Rainbow Race consists of 7 mini-games that take place all over Madrigal. The speed of your flying vehicle, general skill, and luck are the most important elements to winning the race.

