#b#cff0000ffApply for the Rainbow Race!#nb#nc
- What you'll need: Any flying vehicle
- Application Fee: 1,000,000 Penya
- Application Window: 12:01AM ~ 2:00PM on Saturday
- Race Start: Saturdays @ 3:30PM 
- Duration: 2 hours
- How to win: Be the first person to complete all 7 mini-games, return to the Rainbow Race Officer, and select 'Confirm Completion of the Rainbow Race'.
\n#b#cff0000ffPlease note:#nb#nc Once you've applied for the race, you cannot cancel your application.  You must be online before the Race Starts in order to participate.  If you disconnect from the game during the race, you may be disqualified.




