#b#cff0000ff Information#nb#nc
 - The tax rate currently applied to the area.
 - Check the occupying guild and Guild Master.
 - Tax deducted amount is displayed at the tool tip of the item when selling the item to the NPC.
 - Tax added amount is displayed at the tool tip of the item when purchasing the item from the NPC.
 - Occupying Guild can fix the tax rate between 5% ~ 20%. Default tax rate is 0% if there is no occupying guild.
