#b#cff0000ff Entry Information#nb#nc
* Application Period : Secret Room closing  ~ Sunday 12:00
* Area : First sub server of each server set
* Condition
 - Only the Guildmaster applies for the Secret Room
 - Guild level 20 or higher
 - Guild member level 30 or higher
 - GuildMaster must participate
 - Top 8 highest bidding Guilds join(Until the end of the Application Period)
* Process
 - 12:00  Secrect Room opens
 - 13:00  Entry
 - 13:10  Battle starts 
#b#cffff0000『 Secret Room opens at least 1 Guild's application.#nb#nc

#b#cff0000ff Basic Rules#nb#nc
 - Secret Room runs for Eastern area and Western area are independent 
 - First one to kill Lucifer wins
 - Party, Buff skills are cancelled when entering the Secret Room
 - No EXP gained from montsers in the Secret Room. But, EXP penalty activates when killed by a monster
 - Possible to join again in case of getting killed by a monster
 - Possible to join with minimum 1 to maximum 11 Guild members.
#b#cffff0000『 You can not apply for Western Area and Eastern Area at the same time.#nb#nc

#b#cff0000ff Conditon of Victory#nb#nc
 - Mutant Asura appears when all the monsters are dead on the 6th floor of Forsaken Tower.
 - Teleport to Secret Room as Mutant Asura is dead
 -The first ones to kill Lucifer in the Secret Room wins

#b#cff0000ff Rewards#nb#nc
* General Details
 - Tax earning from the area
   (Occupying Guild : Lord : Server = 45 : 45 : 10 )
 - Earned Tax will be sent to Guild Master through Mail at 00:00 next day

* Eastern Area
 - Earning the charge from Forsaken Tower 
   (Occupying Guild : Lord : Server = 45 : 45 : 10 )
 - Earned money will be sent to Guild Master through Mail at 00:00 next day

* Western Area
 - Avaliable to use Hunting Area for occupying Guild through the manager of Western Secret Room
 - All the players in the occupying Guild Hunting Area will be teleported to Darkon at 00:00 Monday
#b#cffff0000『 Occupying Guild dominate the area from 00:00 Monday to Sunday next week.

#b#cff0000ff Commision informaion#nb#nc
 - Application Cancel: Deduct 20% from application fee
              (Returned application fee will be sent to the inventory)
 - Fail to apply:  Deduct 2% from application fee
              (Returned application fee will be sent to mail)
#b#cffff0000『 The top 8 guilds that joined the Secret Room cannot receive the application fee return.#nb#nc
