#b#cff0000ff Information#nb#nc
 - The tax rate applied to the area and the tax rate will be applied.
 - Tax rate can be fixed between 5% ~ 20%.
 - Selling tax is the tax earned when items are sold to a NPC.
 - Purchase tax rate is the tax when items are purchased from a NPC.
 - If an occupying guild does not fix the tax rate, tax will be fixed to 5%. 
#b#cffff0000¡Ø Be careful with the tax rate fix, it can't be changed once it is fixed.#nb#nc
