#b#cff0000ff Confession#nb#nc
You need the power of Angel for your confession.
The angel will decrease your crime(PK) if you increase their EXP.

In order to summon the Angels, you need Sunstone and Moonstone.
The more Oricalkum and Moonstone you use, the higher classed Angel may be summoned.

Higher classed Angel decreases your crime with low EXP.
<Angel>
* Red Angel : 100% based on the character level
* Blue Angel : 60% based on the character level
* Green Angel : 30% based on the character level
* White Angel : 10% based on the character level

¡Ø Possibility for each Angel is shown in the right side of Angel Window.
