// number 삽입 이미지 개수
// serialize 연속으로 이미지 삽입(width hight StartPosition-X StartPosition-Y, center_x, center_y)
// pos 단일로 이미지 삽입 (width hight StartPosition-X StartPosition-Y)
number 24
texture "Theme\Default\ImgNavObj.bmp" 0xffff00ff
serialize 4  5  5  0   0 0 0 // 큰 직업 아이콘 
serialize 2  5  5  0   5 0 0 // 큰 직업 아이콘 
pos 7 7  9 9 n
serialize 6 16 16  0  20 0 0 // 작은 직업 아이콘 
serialize 7 16 16  0  36 0 0 // 작은 직업 아이콘 
serialize 4 16 16 20  0 0 0 // 퀘스트 마크 