The Story of Madrigal and the Three Clown Gods

Chapter 1 
-Birth-

There were once 5 beings of limitless power that, struck by a strange mood,
decided to create a world full of magic and inexhaustible energy.
They met and laid the foundations that would define the world they were to build.


-They created Water, for life to flourish-
-They created Wind, for life to breathe-
-They created Earth, for life to grow-
-They created Fire, to temper the souls of the world's inhabitants-
-They created Lightning, to remind those that watched the skies they were not alone-

Chapter 2 
-Rhisis-

Life in the world, known as Roika, was very good for a long time. 
Inhabitants spread across the continent as the Human Race proliferated. 
The Creators smiled at the life they had created and continued to bless Roika's inhabitants.

The Humans soon grew lonely and begged the Creators to give them companions.
They wished for friends they could turn to in times of difficulty.
The Creators then brought to life the Dwarpets. 
The Dwarpets and Humans developed the rest of their world and lived in harmony 
 for many generations.

Soon, however, the Creators grew tired of watching over the life they had created.  
They prepared to leave Roika forever and return home.
The Dwarpets and Humans begged the Creators to stay.
"Sadly," the Creators said, we cannot. But we will leave someone to watch over you.
The Creators then created Rhisis and made it her duty to protect all life on Roika.

Rhisis protected all life on Roika for thousands of years, but each year her loneliness grew.  
The pain of being left behind began to occupy her mind.

Chapter 3 
-War of the Gods-

Rhisis drew energies from three aspects of herself and created the Three Clown Gods.

She created Bubble, who represented Rishis' joy and purity.
She created Shade, who represented the fear and rage of Rhisis.
She created Iblis, who was Rhisis' apathy personified.

Shade, feeding on Rhisis' anger, set about to destroy Roika and the people that lived there. 
She furiously severed a section of Roika and sent it afloat.
She had hoped that the people living on this chunk of continent would soon perish. 
This chunk of land became known as Madrigal and with the help of the Dwarpets, 
the surviving Humans rebuilt their cities and began to strive once more.

Shade, enraged that she had failed, created a race of creatures known as Masquerpets.  
She sent them to destroy the people of Madrigal. 
Hearing the sounds of battle far below him, Bubble knew he had to intervene.
He struck out at the Masquerpets, splitting Madrigal into 3 main continents and scattering 
the Masquerpets throughout them. 

Iblis watched and did nothing.

Ancient stories speak of eigth Heroes that stood up to Shade and her Masquerpet Army.
It is said that they sacrificed their own lives to defend the inhabitants of Madrigal.

Chapter 4  
-Re-Birth-

The people of Madrigal grew strong but never forgot their friends and family 
 left behind on Roika. 
They now train themselves to face Shade's Masquerpets and prepare for the day...
...when Shade returns to destroy them all. 

