/*
// 나라  개수
LANG_KOR 4 WndQDiaryBG.tga WndQDiaryBG.tga WndQDiaryBG.tga WndQDiaryBG.tga  //파일리스트
*/

LANG_KOR 11 WndCommBanner00.tga WndCommBanner001.tga WndCommBanner002.tga WndCommBanner004.tga WndCommBanner005.tga WndCommBanner006.tga WndCommBanner007.tga WndCommBanner008.tga WndCommBanner009.tga WndCommBanner02.tga WndCommBanner021.tga
LANG_JAP 1 WndForeignBanner.tga
LANG_ENG 1 WndForeignBanner.tga
LANG_TWN 1 WndForeignBanner.tga
LANG_THA 1 WndForeignBanner.tga
LANG_GER 1 WndForeignBanner.tga
LANG_SPA 1 WndForeignBanner.tga
LANG_FRE 1 BanFlyff01.tga